#include "SDIO.h"



void SDCard_1_Bit_Init(void)
{
  GPIO_Setup(GPIOD,2,ALTERNATE_PUSH_PULL_OUTPUT); //CMD
  GPIO_Setup(GPIOC,12,ALTERNATE_PUSH_PULL_OUTPUT); //CLK
	GPIO_Setup(GPIOC,8,ALTERNATE_PUSH_PULL_OUTPUT); //D0
	SDIO ->CLKCR &= ~SDIO_CLKCR_WIDBUS; //SDIO_DO USED
	
}
	//
void SDCard_4_Bit_Init(void)
{
  GPIO_Setup(GPIOD,2,ALTERNATE_PUSH_PULL_OUTPUT); //CMD
  GPIO_Setup(GPIOC,12,ALTERNATE_PUSH_PULL_OUTPUT); //CLK
	GPIO_Setup(GPIOC,8,ALTERNATE_PUSH_PULL_OUTPUT); //D0
  GPIO_Setup(GPIOC,9,ALTERNATE_PUSH_PULL_OUTPUT); //D1
	GPIO_Setup(GPIOC,10,ALTERNATE_PUSH_PULL_OUTPUT); //D2
  GPIO_Setup(GPIOC,11,ALTERNATE_PUSH_PULL_OUTPUT); //D3
	
	SDIO ->CLKCR &= SDIO_CLKCR_WIDBUS_0; //SDIO_D[0:3] USED
}
	//


void SDCard_Power_ON(void)
{
	SDIO -> POWER |= SDIO_POWER_PWRCTRL;
}
//

void SDCard_Power_OFF(void)
{
SDIO -> POWER &= ~SDIO_POWER_PWRCTRL;
}
//

