#include "SPWM.h"





void Single_Phase_SPWM_Init(int frequency)
{
	RCC -> APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN | RCC_APB2ENR_TIM1EN;
	GPIOA -> CRH |= (ALT_PUSH_PULL_OUTPUT << (4*(8-8))) ;
	GPIOB -> CRH |= (ALT_PUSH_PULL_OUTPUT << (4*(13-8)));
	TIM1 -> PSC = (int)(72000000/(frequency*200));
	TIM1 -> ARR = 199;
	TIM1 -> CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1PE ; //PWM1
	TIM1 -> CCER  &= ~(TIM_CCER_CC1P);
	TIM1 -> CCER |= TIM_CCER_CC1NP ;
	TIM1 -> BDTR |= TIM_BDTR_MOE;
	TIM1 -> BDTR |= TIM_BDTR_OSSR;
	TIM1 -> CR1 |= TIM_CR1_ARPE ;
	TIM1 -> EGR |= TIM_EGR_UG;
	TIM1 -> CR1 |= TIM_CR1_CEN;
}

void Single_Phase_Start(){}


//TIM1 -> CCMR1 |= TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2 | TIM_CCMR2_OC1PE ; //PWM2
//TIM1 -> CCMR2 |= TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2 | TIM_CCMR3_OC3PE ; //PWM3
//TIM1 -> CCER  &= ~(TIM_CCER_CC1P | TIM_CCER_CC1P | TIM_CCER_CC1P);
//TIM1 -> CCER |= TIM_CCER_CC1NP | TIM_CCER_CC1NP | TIM_CCER_CC1NP;
//TIM1 -> CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E;
//TIM1 -> BDTR |= TIM_BDTR_MOE;
//TIM1 -> BDTR |= TIM_BDTR_OSSR;
//TIM1 -> CR1 |= TIM_CR1_ARPE ;
//TIM1 -> EGR |= TIM_EGR_UG;
//TIM1 -> CR1 |= TIM_CR1_CEN;

