#include "IrDA.h"




void IrDA_Init(USART_TypeDef *USART)
{

	if(USART == USART1)
	{
		RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_USART1EN;

	}
	else if(USART == USART2)
	{
		RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
		RCC->APB1ENR |= RCC_APB2ENR_USART2EN;
	}
	else if(USART == USART3){
		RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
		RCC->APB1ENR |= RCC_APB2ENR_USART3EN;
	}

	USART->CR3 |= USART_CR3_IREN;
	USART->CR2 &= ~(USART_CR2_LINEN | USART_CR2_STOP | USART_CR2_CLKEN);
	USART -> CR3 &= ~(USART_CR3_SCEN | USART_CR3_HDSEL);
}
